### PR TITLE
Show all Reminders - Closes #1

### LINKED ISSUE #1: See all reminders
- When the user visits the root of the application (e.g. the "/" URL), they should see a list of all of the reminders on the page.
- Each reminder should have a class of `.spec-reminder-item`.

There is a failing test set up in `tests/acceptance/reminder-list-test.js`.

**Hot Tip**: If you name your pull request or even your commit with "Closes #1", it will automatically close this issue when it successfully merged into master.

### PR DESCRIPTION
**Pull request by Jeff-Duke**
## Purpose

We are now able to pass the given acceptance test.  We are getting an error in one of the tests that is related to setup/teardown in the testing suite.

## Approach

We have created a reminder model, appropriate routes, a template for each reminder and added the classes that the test suite was looking for.

### Learning

We looked over example code from ember beats and looked over the ember guides, starting with the ember tutorials.  

### Open Questions and Pre-Merge TODOs

- [x] Are the outstanding failed tests something that we need to address before moving to the next issue?
### Test coverage 

_Briefly describe what tests you have written and why._

No additional tests

@stevekinney @martensonbj @tehviking

### CODE REVIEW

File: app/models/reminder.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import DS from 'ember-data';
+
+export default DS.Model.extend({
+  title: DS.attr('string'),
+  date: DS.attr('date'),
+  notes: DS.hasMany('note'),
```
Comment (stevekinney) [inline app/models/reminder.js]: There isn't anything in the user story specifying the need for a `notes` relationship. It's probably not needed at this time. Since there also isn't a `note` model in the database, I'd just omit it. In the server, `note` is a string. I'd do the same in the model.

File: app/routes/index.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+import Ember from 'ember';
+
+export default Ember.Route.extend({
```
Comment (stevekinney) [inline app/routes/index.js]: This is better suited for a `Reminders` route as we may want to continue showing it in the UI when the user eventually navigates to a note.

File: app/models/reminder.js (hunk 1 above)
Comment (Jeff-Duke) [inline app/models/reminder.js]: this is fixed in the latest commit, also removed the pinned relationship

Comment (Jeff-Duke) [inline app/models/reminder.js]: fixed in new commit

File: app/router.js [hunk 3]
```diff
@@ -7,6 +7,9 @@ const Router = Ember.Router.extend({
 });
 
 Router.map(function() {
+  this.route('reminders', { path: '/' }, function() {
+    this.route('reminder', {path: ':reminder_id'});
```
Comment (stevekinney) [inline app/router.js]: This route is not necessary for this user story and currently isn't tested and shouldn't be in this PR.

File: app/routes/reminder.js [hunk 4]
```diff
@@ -0,0 +1,7 @@
+import Ember from 'ember';
+
+export default Ember.Route.extend({
+  // model(params) {
```
Comment (stevekinney) [inline app/routes/reminder.js]: Commented out code cannot be merged into master. We're not using this route just yet, so it needs to go for now.

File: app/router.js (hunk 3 above)
Comment (Jeff-Duke) [inline app/router.js]: removed 👍

File: app/routes/reminder.js (hunk 4 above)
Comment (Jeff-Duke) [inline app/routes/reminder.js]: removed 👍

File: app/routes/reminders.js [hunk 5]
```diff
@@ -0,0 +1,7 @@
+import Ember from 'ember';
+
+export default Ember.Route.extend({
+  model: function() {
+    return this.store.findAll('reminder');
```
Comment (stevekinney) [inline app/routes/reminders.js]: Per [this documentation](https://guides.emberjs.com/v2.8.0/models/finding-records/), we want to use `this.get('store')` versus `this.store`.

File: app/models/reminder.js [hunk 6]
```diff
@@ -0,0 +1,8 @@
+import DS from 'ember-data';
+
+export default DS.Model.extend({
+  title: DS.attr('string'),
+  date: DS.attr('date'),
+  notes: DS.attr('string'),
+  pinned: DS.attr('boolean')
```
Comment (stevekinney) [inline app/models/reminder.js]: Could you set the default value of this to false?

Comment (Jeff-Duke) [inline app/models/reminder.js]: fixed :octocat:

File: app/models/reminder.js [hunk 7]
```diff
@@ -0,0 +1,8 @@
+import DS from 'ember-data';
+
+export default DS.Model.extend({
+  title: DS.attr('string'),
+  date: DS.attr('date'),
+  notes: DS.attr('string'),
+  pinned: DS.attr(false)
```
Comment (martensonbj) [inline app/models/reminder.js]: Syntax needs to be a little different to set a default value. Check out [this example in the docs](https://guides.emberjs.com/v2.4.0/models/defining-models/#toc_options)

Comment (Jeff-Duke) [inline app/models/reminder.js]: updated the syntax 👍
